### ISSUE TITLE
reset fails on nds

### ISSUE THREAD

**Issue by non** [asiekierka/uxnds#17] opened 2023-04-25 14:55 UTC
I just installed uxnds037 onto a 2022 R4 card.

I copied the following files to the root directory of the card:

- uxn/
- uxnds_debug.nds
- uxnds.nds
- uxnds_profile.nds

When launching any of the uxnds programs I see the uxn launcher and can load and run uxn roms (such as catclock, calc, etc.). However, when I reset (start+select followed by A) I get an error:

```
Resetting...
Error Load: Failed
```

I get this no matter which of the 3 uxn programs I run. I'm using the default launcher for this card (it shows up on the main DS screen as "deep labyrinth"). I'd rather not overwrite the launcher (I'm not very experienced with DS hacking) but am willing to do so to help test if you think that nds-hb-menu would fix the issue.

**Comment by non** [comment] 2023-04-25 15:02
I should add that this is a DS Lite.

**Comment by LordRembo** [comment] 2023-05-01 20:55
Using the last version of uxnds, I can confirm the reset doesn't work on DS Lite, nor on New 4DS (using either Twilight++ or directly from my flash cart).

**Comment by asiekierka** [comment] 2023-05-02 07:48
Duplicate of #10. I'll look into it soon, hopefully.

**Closed as completed by asiekierka** 2023-05-02 07:48 UTC
Labels: duplicate
